---
title: "Data Wrangling II"
author: "Lucia Wang lw3061"
date: "2023-09-21"
output: github_document
---

```{r}
library(tidyverse)
```

Import FAS litters and pups.
```{r}
litters_df =
  read_csv(file="data_import_examples/FAS_litters.csv")

litters_df = 
  janitor ::clean_names(litters_df)

pups_df = read_csv(file="data_import_examples/FAS_pups.csv")

pups_df = janitor :: clean_names(pups_df)
```

## `select`
`select` is used to select columns
```{r}
select(litters_df, group, litter_number,gd0_weight)

select(litters_df, group, gd0_weight:gd_of_birth)

select(litters_df, group, starts_with("pups"))

select(litters_df, -litter_number)

select(litters_df, starts_with("gd"))

select(litters_df, group, litter_id = litter_number)

select(litters_df, group, litter_id = litter_number, everything())

select(litters_df, gd0_weight, everything())
```

`select` vs `pull`
```{r}
select(litters_df, group)

pull(litters_df, group)
```

Learning assessment 1
```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## `filter`
will get more complicated than `select`. based on something inside your dataframe. use `==` to check if things are true (logical statement within the function)
```{r}
filter(litters_df, group == "Con7")

filter(litters_df, group != "Con7")

filter(litters_df, gd0_weight > 20)

filter(litters_df, group == "Con7" | group == "Con8")

filter(litters_df, group %in% c("Con7","Con8"))

filter(litters_df, !(group == "Con7"))
```

what about missing values?
```{r}
drop_na(litters_df)
drop_na(litters_df, gd0_weight)
```

## `mutate`
to add or change variables, depending on existing variables

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight)

mutate(litters_df, group = str_to_lower(group))

mutate(
  litters_df,
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group)
)
```


